export const workouts = {
  Monday: {
    title: "Heavy Squat Day",
    focus: "Raw strength + pulling volume",
    exercises: [
      ["Box Jump", "3 x 3", "RPE 5"],
      ["Back Squat", "5 x 5", "175 lb · RPE 6–7"],
      ["Bench Press", "4 x 6", "115 lb · RPE 7"],
      ["Pull-up", "4 x 5", "Bodyweight"],
      ["Romanian Deadlift", "3 x 8", "RPE 7"],
      ["Face Pull", "3 x 15", "Easy"],
      ["Cable Y Raise", "2 x 12", "Easy"],
      ["Hammer Curl", "2 x 12", "Easy"],
      ["Cable Chop", "3 x 10/side", "Controlled"],
      ["Ab Wheel", "3 x 8", "Controlled"],
      ["Farmer Carry", "4 x 40 yd", "Heavy"],
    ],
  },
  Wednesday: {
    title: "Light Squat + Press",
    focus: "Technique + shoulder health",
    exercises: [
      ["KB Swing", "4 x 8", "Fast"],
      ["Tempo Squat", "4 x 5", "RPE 6"],
      ["Standing Press", "5 x 5", "75 lb · RPE 6–7"],
      ["Single-arm Cable Row", "4 x 10/side", "Start left"],
      ["Neutral-grip Pull-up", "3 sets", "Stop 2 reps short"],
      ["GHD Hip Extension", "3 x 12", "Controlled"],
      ["Mace 360", "3 x 10/dir", "Light"],
      ["Band External Rotation", "3 x 15", "Easy"],
      ["Chin Tucks", "2 x 15", "Easy"],
      ["Side Plank", "3 x 30–45 sec", "Controlled"],
    ],
  },
  Friday: {
    title: "Front Squat + Athletic Strength",
    focus: "Medium squat + carries",
    exercises: [
      ["Hang Power Clean", "4 x 3", "Fast"],
      ["Front Squat", "4 x 5", "115 lb · RPE 6"],
      ["Incline DB Press", "4 x 8", "RPE 7"],
      ["Chest-supported DB Row", "4 x 10", "RPE 7"],
      ["Bulgarian Split Squat", "3 x 8/leg", "Start left"],
      ["GHD Glute-Ham Raise", "3 x 6–8", "Controlled"],
      ["Bottom-up KB Carry", "3 x 30 yd/arm", "Moderate"],
      ["Cable Lift", "3 x 10/side", "Controlled"],
      ["Dead Hang", "3 sets", "Near max"],
      ["Suitcase Carry", "3 x 40 yd/side", "Heavy"],
    ],
  },
};

export const warmups = {
  Monday: [
    "Foam roll T-spine, glutes, hip flexors — 3 min",
    "Deep squat hold — 60 sec",
    "Ankle rocks — 15/side",
    "90/90 hip switches — 10/side",
    "Monster walks — 15/side",
    "Single-leg glute bridge — 10/side",
    "Dead bug — 8/side",
    "Box jump ramp-up — 3 x 3",
  ],
  Wednesday: [
    "Foam roll T-spine and lats — 3 min",
    "Thoracic rotations — 10/side",
    "Band pull-aparts — 20",
    "Wall slides — 12",
    "Serratus wall slides — 10",
    "Band external rotation — 15/side",
    "Chin tucks — 10",
    "Light mace 360 — 2 x 10/dir",
  ],
  Friday: [
    "Foam roll T-spine, glutes, hip flexors — 3 min",
    "World's Greatest Stretch — 5/side",
    "90/90 hip switches — 10/side",
    "Mace halo — 2 x 10/dir",
    "Monster walks — 15/side",
    "Pallof press — 10/side",
    "Kettlebell swing ramp-up — 2 x 8",
    "Empty bar front squat — 2 x 5",
  ],
};

export const targets = [
  ["Back Squat", 230, 315],
  ["Front Squat", 170, 245],
  ["Deadlift", 250, 365],
  ["Bench Press", 160, 225],
  ["Overhead Press", 100, 145],
  ["Pull-ups", 10, 18],
];