export const phases = {
  Phase1: {
    name: "Weeks 1–4: Foundation Strength",
    Monday: {
      title: "Maximum Force Production",
      focus: "Heavy squat, bench, pull-up, hinge, rotation, carries",
      exercises: [
        ["Back Squat", "5 x 5", "RPE 6–7"],
        ["Bench Press", "4 x 6", "RPE 7"],
        ["Weighted Pull-Up", "4 x 5", "RPE 7"],
        ["Romanian Deadlift", "3 x 8", "RPE 7"],
        ["Chest-Supported Row", "3 x 10", "Controlled"],
        ["Face Pull", "2 x 15", "Easy"],
        ["Cable Y Raise", "2 x 12", "Easy"],
        ["Ab Wheel", "3 x 8", "Controlled"],
        ["Pallof Press", "2 x 10/side", "Anti-rotation"],
        ["Farmer Carry", "3 x 40 yd", "Heavy"],
        ["Wrist Extensor Eccentrics", "2 x 15", "Elbow rehab"],
        ["Chin Tucks", "2 x 15", "Neck reset"],
      ],
    },
    Wednesday: {
      title: "Movement Quality + Strength",
      focus: "Light squat, press, unilateral strength, shoulder durability",
      exercises: [
        ["Kettlebell Swing", "4 x 8", "Fast"],
        ["Tempo Back Squat", "4 x 5", "RPE 6"],
        ["Standing Press", "5 x 5", "RPE 6–7"],
        ["Single-Leg RDL", "3 x 8/side", "Start left"],
        ["Single-Arm Cable Row", "4 x 10/side", "Start left"],
        ["Neutral-Grip Pull-Up", "3 x 6–8", "Leave 2 reps"],
        ["GHD Hip Extension", "3 x 10", "Controlled"],
        ["Trap-3 Raise", "2 x 15", "Easy"],
        ["Cable Chop", "3 x 10/side", "Rotation"],
        ["Bottom-Up KB Carry", "3 x 30 yd/arm", "Shoulder stability"],
        ["Chin Tucks", "2 x 15", "Neck reset"],
      ],
    },
    Friday: {
      title: "Athletic Strength",
      focus: "Hang power clean, front squat, unilateral work, rotation, grip",
      exercises: [
        ["Hang Power Clean", "5 x 3", "RPE 5–6"],
        ["Front Squat", "4 x 5", "RPE 6–7"],
        ["Incline DB Press", "4 x 8", "RPE 7"],
        ["Chest-Supported Row", "4 x 10", "Controlled"],
        ["Bulgarian Split Squat", "3 x 8/leg", "Start left"],
        ["GHD Glute-Ham Raise", "3 x 6–8", "Controlled"],
        ["Cable Lift", "3 x 10/side", "Rotation"],
        ["Suitcase Carry", "3 x 40 yd/side", "Anti-lateral flexion"],
        ["Dead Hang", "3 x max", "Grip"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
  },

  Phase2: {
    name: "Weeks 5–8: Strength Development",
    Monday: {
      title: "Maximum Force Production",
      focus: "Heavier squat, bench, pull-up, hinge, carries",
      exercises: [
        ["Box Jump", "4 x 3", "Explosive"],
        ["Back Squat", "5 x 4", "RPE 7–8"],
        ["Bench Press", "5 x 5", "RPE 7–8"],
        ["Weighted Pull-Up", "5 x 4", "RPE 7–8"],
        ["Romanian Deadlift", "3 x 6", "RPE 7"],
        ["Chest-Supported Row", "3 x 8", "Controlled"],
        ["Face Pull", "2 x 15", "Easy"],
        ["Ab Wheel", "3 x 10", "Controlled"],
        ["Pallof Press", "2 x 12/side", "Anti-rotation"],
        ["Farmer Carry", "4 x 40 yd", "Heavy"],
        ["Wrist Extensor Eccentrics", "2 x 15", "Elbow rehab"],
        ["Chin Tucks", "2 x 15", "Neck reset"],
      ],
    },
    Wednesday: {
      title: "Movement Quality + Strength",
      focus: "Tempo squat, press strength, unilateral control",
      exercises: [
        ["Kettlebell Swing", "5 x 6", "Fast"],
        ["Tempo Back Squat", "4 x 4", "RPE 6–7"],
        ["Standing Press", "5 x 4", "RPE 7"],
        ["Single-Leg RDL", "3 x 8/side", "Start left"],
        ["Single-Arm Cable Row", "4 x 8/side", "Start left"],
        ["Neutral-Grip Pull-Up", "4 x 6", "Leave 1–2 reps"],
        ["GHD Hip Extension", "3 x 8", "Controlled"],
        ["Trap-3 Raise", "2 x 15", "Easy"],
        ["Cable Chop", "3 x 10/side", "Rotation"],
        ["Bottom-Up KB Carry", "3 x 40 yd/arm", "Shoulder stability"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
    Friday: {
      title: "Athletic Strength",
      focus: "Strength-speed, front squat, carries, rotation",
      exercises: [
        ["Hang Power Clean", "6 x 2", "RPE 6–7"],
        ["Front Squat", "4 x 4", "RPE 7"],
        ["Incline DB Press", "4 x 6", "RPE 7"],
        ["Chest-Supported Row", "4 x 8", "Controlled"],
        ["Bulgarian Split Squat", "3 x 8/leg", "Start left"],
        ["GHD Glute-Ham Raise", "3 x 6", "Controlled"],
        ["Cable Lift", "3 x 10/side", "Rotation"],
        ["Suitcase Carry", "4 x 40 yd/side", "Heavy"],
        ["Dead Hang", "3 x max", "Grip"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
  },

  Phase3: {
    name: "Weeks 9–12: Strength to Power",
    Monday: {
      title: "Force Production",
      focus: "Lower volume, higher quality, strength maintenance",
      exercises: [
        ["Box Jump", "5 x 2", "Explosive"],
        ["Back Squat", "4 x 3", "RPE 7–8"],
        ["Bench Press", "4 x 4", "RPE 7–8"],
        ["Weighted Pull-Up", "4 x 4", "RPE 7–8"],
        ["Romanian Deadlift", "3 x 5", "RPE 7"],
        ["Chest-Supported Row", "3 x 8", "Controlled"],
        ["Face Pull", "2 x 15", "Easy"],
        ["Ab Wheel", "3 x 10", "Controlled"],
        ["Pallof Press", "2 x 12/side", "Anti-rotation"],
        ["Farmer Carry", "4 x 50 yd", "Heavy"],
        ["Wrist Extensor Eccentrics", "2 x 15", "Elbow rehab"],
        ["Chin Tucks", "2 x 15", "Neck reset"],
      ],
    },
    Wednesday: {
      title: "Movement Quality + Resilience",
      focus: "Lower fatigue, clean movement, shoulder/hip durability",
      exercises: [
        ["Kettlebell Swing", "4 x 6", "Fast"],
        ["Tempo Back Squat", "3 x 4", "RPE 6"],
        ["Standing Press", "4 x 4", "RPE 7"],
        ["Single-Leg RDL", "3 x 6/side", "Start left"],
        ["Single-Arm Cable Row", "3 x 8/side", "Start left"],
        ["Neutral-Grip Pull-Up", "3 x 6", "Leave 2 reps"],
        ["GHD Hip Extension", "3 x 8", "Controlled"],
        ["Trap-3 Raise", "2 x 15", "Easy"],
        ["Cable Chop", "3 x 10/side", "Rotation"],
        ["Bottom-Up KB Carry", "3 x 40 yd/arm", "Shoulder stability"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
    Friday: {
      title: "Athletic Strength",
      focus: "Power, front squat strength, rotation, carries",
      exercises: [
        ["Hang Power Clean", "6 x 2", "RPE 6–7"],
        ["Front Squat", "4 x 3", "RPE 7"],
        ["Incline DB Press", "3 x 6", "RPE 7"],
        ["Chest-Supported Row", "3 x 8", "Controlled"],
        ["Bulgarian Split Squat", "2 x 8/leg", "Start left"],
        ["GHD Glute-Ham Raise", "3 x 5", "Controlled"],
        ["Cable Lift", "3 x 10/side", "Rotation"],
        ["Suitcase Carry", "4 x 50 yd/side", "Heavy"],
        ["Dead Hang", "3 x max", "Grip"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
  },

  Phase4: {
    name: "Weeks 13–16: Performance + Consolidation",
    Monday: {
      title: "Maximum Strength",
      focus: "Strong, fast, durable, low fatigue",
      exercises: [
        ["Box Jump", "5 x 2", "Explosive"],
        ["Back Squat", "3 x 3", "RPE 7–8"],
        ["Bench Press", "3 x 4", "RPE 7"],
        ["Weighted Pull-Up", "4 x 3", "RPE 7–8"],
        ["Romanian Deadlift", "3 x 5", "RPE 7"],
        ["Chest-Supported Row", "3 x 8", "Controlled"],
        ["Face Pull", "2 x 15", "Easy"],
        ["Pallof Press", "2 x 12/side", "Anti-rotation"],
        ["Ab Wheel", "3 x 10", "Controlled"],
        ["Farmer Carry", "5 x 40 yd", "Heavy"],
        ["Chin Tucks", "2 x 15", "Neck reset"],
      ],
    },
    Wednesday: {
      title: "Durability + Movement",
      focus: "Lowest fatigue day, maintain quality",
      exercises: [
        ["Kettlebell Swing", "3 x 8", "Fast"],
        ["Tempo Squat", "3 x 3", "RPE 6"],
        ["Standing Press", "3 x 5", "RPE 6–7"],
        ["Single-Leg RDL", "2 x 8/side", "Start left"],
        ["Single-Arm Cable Row", "3 x 8/side", "Start left"],
        ["Trap-3 Raise", "2 x 15", "Easy"],
        ["Cable Chop", "2 x 12/side", "Rotation"],
        ["Bottom-Up KB Carry", "3 x 40 yd/arm", "Shoulder stability"],
        ["GHD Hip Extension", "2 x 10", "Controlled"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
    Friday: {
      title: "Athletic Performance",
      focus: "Power, front squat, rotation, carries, grip",
      exercises: [
        ["Hang Power Clean", "6/6/5/4 x 2", "Weeks 13–16 · RPE 6–7"],
        ["Front Squat", "4/4/3/3 x 3", "Weeks 13–16 · RPE 7"],
        ["Incline DB Press", "3 x 6", "RPE 7"],
        ["Chest-Supported Row", "3 x 8", "Controlled"],
        ["Bulgarian Split Squat", "2 x 8/leg", "Start left"],
        ["GHD Glute-Ham Raise", "3 x 5", "Controlled"],
        ["Cable Lift", "3 x 10/side", "Rotation"],
        ["Suitcase Carry", "5 x 40 yd/side", "Heavy"],
        ["Dead Hang", "3 x max", "Grip"],
        ["Band Neck Series", "2 rounds", "Neck durability"],
      ],
    },
  },
};

export const warmups = {
  Monday: [
    "3–5 min Air Bike or brisk walk",
    "Crocodile breathing — 1 min",
    "McGill curl-up — 2 x 5 with 10-sec holds",
    "Bird dog — 2 x 5/side",
    "Side plank — 2 x 20–30 sec/side",
    "Deep squat hold — 60 sec",
    "Hip airplanes — 2 x 5/side",
    "Ankle rocks — 15/side",
    "90/90 hip switches — 10/side",
    "Monster walks — 2 x 15/side",
    "Box jump ramp-up — 3 x 3",
    "Squat ramp-up sets",
  ],
  Wednesday: [
    "5 min Air Bike",
    "Crocodile breathing — 1 min",
    "McGill curl-up — 2 x 5 with 10-sec holds",
    "Bird dog — 2 x 5/side",
    "Side plank — 2 x 20–30 sec/side",
    "Thoracic rotations — 10/side",
    "Band pull-aparts — 2 x 20",
    "Wall slides — 2 x 12",
    "Serratus wall slides — 2 x 10",
    "Band external rotation — 2 x 15/side",
    "Light mace 360 — 2 x 10/direction",
  ],
  Friday: [
    "5 min Air Bike",
    "Crocodile breathing — 1 min",
    "McGill curl-up — 2 x 5 with 10-sec holds",
    "Bird dog — 2 x 5/side",
    "Side plank — 2 x 20–30 sec/side",
    "World's Greatest Stretch — 5/side",
    "90/90 hip switches — 10/side",
    "Mace halo — 2 x 10/direction",
    "Pallof press — 2 x 10/side",
    "Front squat ramp-up sets",
  ],
};

export const conditioning = {
  Tuesday: "Zone 2 trail run or surf — 45–75 min",
  Thursday: "Air Bike intervals — 20–30 sec hard / 90–100 sec easy",
  Saturday: "Surf, trail run, freedive, or spearfish based on recovery",
  Sunday: "Recovery walk, mobility, breathing",
};

export const targets = [
  ["Back Squat", 230, 315],
  ["Front Squat", 170, 245],
  ["Deadlift", 250, 365],
  ["Bench Press", 160, 225],
  ["Overhead Press", 100, 145],
  ["Pull-ups", 10, 18],
];